"""esquema inicial

Revision ID: 0001
Revises:
Create Date: 2026-09-26 10:08:42.158229
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checkpoints",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_checkpoints")),
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("profile", sa.String(length=12), nullable=False),
        sa.Column("decision_id", sa.String(length=12), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("base_asset", sa.String(length=16), nullable=False),
        sa.Column("quote_asset", sa.String(length=16), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("entry_mode", sa.String(length=24), nullable=False),
        sa.Column("policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("planned_qty", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("planned_price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("protection_list_id", sa.String(length=36), nullable=False),
        sa.Column("protection_seq", sa.Integer(), nullable=False),
        sa.Column("entry_qty", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("entry_quote", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("entry_price", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("protected_qty", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("exit_quote", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("exit_price", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("realized_pnl", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("exit_reason", sa.String(length=24), nullable=True),
        sa.Column("fees", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
        sa.UniqueConstraint("decision_id", name=op.f("uq_positions_decision_id")),
    )
    op.create_index(op.f("ix_positions_state"), "positions", ["state"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("severity", sa.String(length=8), nullable=False),
        sa.Column("position_id", sa.BigInteger(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["position_id"], ["positions.id"], name=op.f("fk_events_position_id_positions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index("ix_events_created_at", "events", ["created_at"], unique=False)
    op.create_index(op.f("ix_events_position_id"), "events", ["position_id"], unique=False)
    op.create_table(
        "exchange_orders",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("position_id", sa.BigInteger(), nullable=True),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("order_list_id", sa.BigInteger(), nullable=False),
        sa.Column("client_order_id", sa.String(length=36), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("type", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("orig_qty", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("executed_qty", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("cumulative_quote_qty", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("stop_price", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("trailing_delta", sa.Integer(), nullable=True),
        sa.Column("expiry_reason", sa.String(length=48), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["position_id"], ["positions.id"], name=op.f("fk_exchange_orders_position_id_positions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exchange_orders")),
        sa.UniqueConstraint("symbol", "order_id", name="uq_exchange_orders_symbol_order"),
    )
    op.create_index(
        op.f("ix_exchange_orders_client_order_id"),
        "exchange_orders",
        ["client_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exchange_orders_position_id"), "exchange_orders", ["position_id"], unique=False
    )
    op.create_table(
        "fills",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("position_id", sa.BigInteger(), nullable=True),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("trade_id", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("qty", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("quote_qty", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("commission", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("commission_asset", sa.String(length=16), nullable=False),
        sa.Column("is_buyer", sa.Boolean(), nullable=False),
        sa.Column("is_maker", sa.Boolean(), nullable=False),
        sa.Column("trade_time", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["position_id"], ["positions.id"], name=op.f("fk_fills_position_id_positions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fills")),
        sa.UniqueConstraint("symbol", "trade_id", name="uq_fills_symbol_trade"),
    )
    op.create_index(op.f("ix_fills_position_id"), "fills", ["position_id"], unique=False)
    op.create_table(
        "intents",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("position_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("endpoint", sa.String(length=16), nullable=False),
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["position_id"], ["positions.id"], name=op.f("fk_intents_position_id_positions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intents")),
        sa.UniqueConstraint("client_id", name=op.f("uq_intents_client_id")),
    )
    op.create_index(op.f("ix_intents_position_id"), "intents", ["position_id"], unique=False)
    op.create_index(op.f("ix_intents_status"), "intents", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_intents_status"), table_name="intents")
    op.drop_index(op.f("ix_intents_position_id"), table_name="intents")
    op.drop_table("intents")
    op.drop_index(op.f("ix_fills_position_id"), table_name="fills")
    op.drop_table("fills")
    op.drop_index(op.f("ix_exchange_orders_position_id"), table_name="exchange_orders")
    op.drop_index(op.f("ix_exchange_orders_client_order_id"), table_name="exchange_orders")
    op.drop_table("exchange_orders")
    op.drop_index(op.f("ix_events_position_id"), table_name="events")
    op.drop_index("ix_events_created_at", table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_positions_state"), table_name="positions")
    op.drop_table("positions")
    op.drop_table("checkpoints")
    # ### end Alembic commands ###
