"""market analyst

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-26 21:39:26.227462
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_usage",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("purpose", sa.String(length=24), nullable=False),
        sa.Column("model", sa.String(length=48), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_creation_input_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_read_input_tokens", sa.Integer(), nullable=False),
        sa.Column("web_search_requests", sa.Integer(), nullable=False),
        sa.Column("web_fetch_requests", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_usage")),
    )
    op.create_index(op.f("ix_llm_usage_at"), "llm_usage", ["at"], unique=False)
    op.create_table(
        "news_items",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("dedupe_key", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("assets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("relevance", sa.Float(), nullable=True),
        sa.Column("category", sa.String(length=16), nullable=True),
        sa.Column("severity", sa.String(length=16), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_news_items")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_news_items_dedupe_key")),
    )
    op.create_index(
        op.f("ix_news_items_published_at"), "news_items", ["published_at"], unique=False
    )
    op.create_table(
        "research_reports",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=48), nullable=False),
        sa.Column("prompt_version", sa.String(length=16), nullable=False),
        sa.Column("view", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("draft", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("adjustments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_reports")),
    )
    op.create_index(
        op.f("ix_research_reports_created_at"), "research_reports", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_research_reports_created_at"), table_name="research_reports")
    op.drop_table("research_reports")
    op.drop_index(op.f("ix_news_items_published_at"), table_name="news_items")
    op.drop_table("news_items")
    op.drop_index(op.f("ix_llm_usage_at"), table_name="llm_usage")
    op.drop_table("llm_usage")
    # ### end Alembic commands ###
