"""telemetry

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-26 22:27:11.029126
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telemetry_snapshots",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("equity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("day_start_equity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("peak_equity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("drawdown_pct", sa.Float(), nullable=False),
        sa.Column("exposure", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("active_positions", sa.Integer(), nullable=False),
        sa.Column("api_error_rate", sa.Float(), nullable=False),
        sa.Column("used_weight_1m", sa.Integer(), nullable=True),
        sa.Column("clock_offset_ms", sa.Integer(), nullable=True),
        sa.Column("btc_change_1h", sa.Float(), nullable=True),
        sa.Column("quote_deviation", sa.Float(), nullable=True),
        sa.Column("fear_greed", sa.Integer(), nullable=True),
        sa.Column("states", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("profiles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telemetry_snapshots")),
    )
    op.create_index(op.f("ix_telemetry_snapshots_at"), "telemetry_snapshots", ["at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_telemetry_snapshots_at"), table_name="telemetry_snapshots")
    op.drop_table("telemetry_snapshots")
    # ### end Alembic commands ###
